steps:
  - label: "Sanity check"
    command: pwd && ls
    key: "pre-build"
    working_directory: "/"

  - label: "This is the first step"
    command: ./buildkite/print_numbers.sh
    key: "build"
  
  - label: "This will be done after numbers are printed"
    command: echo "All done"
    key: "finish"
    

