steps:
  - label: "Sanity check"
    command: pwd && ls
    key: "pre-build"

  - label: "This is the first step"
    command: ./.buildkite/print_numbers.sh
    key: "build"
  
  - label: "This will be done after numbers are printed"
    command: echo "All done"
    key: "finish"

  - label: "This step will fail"
    command: ./spaghetti
    key: "failing step"

  - label: "This step might still run"
    command: echo "still running"
    key: "still running"

  - label: "This step shouldnt still run"
    command: echo "everything passed!"
    key: "Everything passed"
    depends_on: "failing step"
    

